// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDegOhngqmcMdugbFgOq-E34YM4-VV2TjA',
    appId: '1:305925256226:web:231153c60b544e62e7467b',
    messagingSenderId: '305925256226',
    projectId: 'recipes-7afa9',
    authDomain: 'recipes-7afa9.firebaseapp.com',
    storageBucket: 'recipes-7afa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUu1VXTUFlXi5Ir4NgJ6FHDT8wRWKtXc',
    appId: '1:305925256226:android:e231a2cbc289ec11e7467b',
    messagingSenderId: '305925256226',
    projectId: 'recipes-7afa9',
    storageBucket: 'recipes-7afa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVV_bqsJMcMkSD9Rjs4ZXhPuJt_pj-FU',
    appId: '1:305925256226:ios:d381b1f91b4e41c5e7467b',
    messagingSenderId: '305925256226',
    projectId: 'recipes-7afa9',
    storageBucket: 'recipes-7afa9.firebasestorage.app',
    iosBundleId: 'com.example.recipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVV_bqsJMcMkSD9Rjs4ZXhPuJt_pj-FU',
    appId: '1:305925256226:ios:d381b1f91b4e41c5e7467b',
    messagingSenderId: '305925256226',
    projectId: 'recipes-7afa9',
    storageBucket: 'recipes-7afa9.firebasestorage.app',
    iosBundleId: 'com.example.recipes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDegOhngqmcMdugbFgOq-E34YM4-VV2TjA',
    appId: '1:305925256226:web:e5f81f30c785c481e7467b',
    messagingSenderId: '305925256226',
    projectId: 'recipes-7afa9',
    authDomain: 'recipes-7afa9.firebaseapp.com',
    storageBucket: 'recipes-7afa9.firebasestorage.app',
  );
}
